require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot

inherit_gem:
  citizens-advice-style:
    - default.yml
    - default-rails.yml

Lint/MissingSuper:
  Exclude:
    # Calls to super in subclasses of ViewComponent::Base aren't needed
    # by default and can change the behaviour of **kwargs so we
    # exclude component classes from this rule
    # See https://github.com/ViewComponent/view_component/discussions/1545
    # See https://github.com/citizensadvice/design-system/pull/2416
    - "app/components/**/*.rb"

Lint/UnusedBlockArgument:
  Exclude:
    # Cucumber's 'Around' hook needs arguments of 'scenario' & 'block' to work
    # It reads 'scenario' from the .feature files, but rubocop interprets
    # 'scenario' as an unused block argument
    - "features/support/hooks.rb"

RSpec/NestedGroups:
  # Set the max to a more reasonable limit of 4
  Max: 4


Rails/I18nLocaleTexts:
  Exclude:
    # We aren't translating the error messages into another language
    # so it's simpler to have the error msgs next to the validation rules
    - "app/models/daily_usage_creation/steps/*.rb"