[tool.poetry]
name = "energy-comparison-table-cdk"
version = "0.1.0"
description = "CDK app for the Energy Comparison Table"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aws-cdk-lib = "2.90.0"
constructs = ">=10.0.0,<11.0.0"
pytest = "6.2.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
