{{- range  $name, $config := .Values.vaultSecrets -}}
{{ if $config.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-secret-{{ $name }}
  labels:
    {{- include "casebook.labels" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    # the Vault store 'vault' is created by the platform
    name: vault
    kind: SecretStore
  target:
    # the k8s secret name.
    # Used in app/chart/templates/_helpers.tpl#casebook.external_secrets_ref
    name: vault-secret-{{ $name }}
    creationPolicy: Owner
  data:
{{- range  $k, $v := $config.mappings }}
  - secretKey: {{default $k $v}} # the key in the k8s secret, defaults to the key name in vault
    remoteRef:
      key: {{ $config.path }} # path in vault
      property: {{ $k }} # the key in vault secret
{{- end -}}
{{- end -}}
{{- end -}}
