apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "energy-apps.fullname" . }}
  labels:
    {{- include "energy-apps.labels" . | nindent 4 }}
    tags.datadoghq.com/env: {{ .Values.datadog.labels.env }}
    tags.datadoghq.com/service: "energy-apps"
    tags.datadoghq.com/version: {{ .Values.image.tag }}
  annotations:
{{- if .Values.annotations -}}
{{ toYaml .Values.annotations | nindent 4 }}
{{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "energy-apps.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        ad.datadoghq.com/energy-apps.logs: >-
          [{
              "source":"ruby",
              "sourcecategory":"sourcecode",
              "service":"energy-apps",
              "log_processing_rules": [{
                "type": "exclude_at_match",
                "name": "exclude_status_heartbeat",
                "pattern" : "\"path\":\"/status\""
              }]
          }]
      labels:
        {{- include "energy-apps.selectorLabels" . | nindent 8 }}
        tags.datadoghq.com/env: {{ .Values.datadog.labels.env }}
        tags.datadoghq.com/service: "energy-apps"
        tags.datadoghq.com/version: {{ .Values.image.tag }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "energy-apps.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_VERSION
              value: {{  .Values.image.tag }}
          {{- if .Values.envVars }}
          {{- range $name, $val := .Values.envVars }}
            - name: {{ $name }}
              value: {{ $val }}
          {{ end }}
          {{- end }}
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          {{ if .Values.secrets -}}
          envFrom:
            - secretRef:
                name: {{ include "energy-apps.fullname" . }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          lifecycle:
            preStop:
              sleep:
                seconds: 10
          readinessProbe:
            httpGet:
              path: /status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
