{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "energy-apps.fullname" . }}
  labels:
    {{- include "energy-apps.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.secrets }}
  {{$key}}: {{$val | b64enc | quote }}
{{- end -}}
{{- end -}}
