name: Linting
on:
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  node-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - run: yarn install
      - run: yarn run lint
