name: Linting
on:
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  Lint:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup node"
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: "Install npm packages"
        run: yarn install

      - name: "Setup ruby"
        uses: ruby/setup-ruby@v1

      - name: "Install gems"
        run: |
          bundle lock --add-platform x86_64-linux
          bundle install

      - name: "Node lint"
        run: yarn run lint

      - name: "Ruby lint"
        run: bundle exec rubocop --format progress --format json --out rubocop.json

      - name: "Annotate rubocop failures"
        uses: duderman/rubocop-annotate-action@v0.1.0
        with:
          path: rubocop.json
        if: ${{ failure() }}

      - name: "Haml lint"
        run: bundle exec haml-lint app/**/*.html.haml
