name: Lint and test
on:
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "Setup node"
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: "Install npm packages"
        uses: bahmutov/npm-install@v1

      - name: "Node lint"
        run: yarn run lint

      - name: "Ruby lint"
        run: bundle exec rubocop --format progress --format github

      - name: "Haml lint"
        run: bundle exec haml-lint app/**/*.html.haml

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "Setup node"
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: "Install npm packages"
        uses: bahmutov/npm-install@v1

      - name: "Precompile assets"
        run: bundle exec rails assets:precompile

      - name: "Rspec"
        run: bundle exec rspec

  audit:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "Bundle audit"
        run: bundle exec bundle-audit

      - name: "Brakeman audit"
        run: bundle exec brakeman

      - name: "License audit"
        run: bundle exec license_finder

  feature-test:
    runs-on: ubuntu-latest
    environment: dev
    env:
      RAILS_ENV: test
      CONTENTFUL_CDA_TOKEN: ${{ secrets.CONTENTFUL_CDA_TOKEN }}
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_ENVIRONMENT_ID: ${{ secrets.CONTENTFUL_ENVIRONMENT_ID }}
    needs: lint
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "Setup node"
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: "Install npm packages"
        uses: bahmutov/npm-install@v1

      - name: "Precompile assets"
        run: bundle exec rails assets:precompile

      - name: "Cucumber"
        run: bundle exec cucumber

      # Archive test logs
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-logs
          path: ./log/test.log
          retention-days: 7
